### ISSUE TITLE
Program error，Wrong contents such as details

### ISSUE THREAD

**Issue by jiankewei** [AppLozic/ApplozicSwift#70]
An SSL error has occurred and a secure connection to the server cannot be made., _kCFStreamErrorDomainKey=3, NSErrorFailingURLKey=https://applozic.appspot.com/rest/ws/aws/file/url, _kCFStreamErrorCodeKey=-9800}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://applozic.appspot.com/rest/ws/aws/file/url, NSErrorFailingURLStringKey=https://applozic.appspot.com/rest/ws/aws/file/url, _kCFStreamErrorDomainKey=3} && ERROR:CODE : -1200

**Comment by ShivamPokhriyal** [comment]
@jiankewei In which country are you using the app?

**Comment by jiankewei** [comment]
> @jiankewei您在哪个国家/地区使用该应用？



I am in Shanghai, China.

**Comment by ShivamPokhriyal** [comment]
@jiankewei This error is coming because google app engine is inaccessible in CHINA. 
So You need to do following workaround:

Update your info.plist: Add the following key value pairs if you haven't

<key>APPLOZIC_PRODUCTION</key>
<dict>
<key>AL_FILE_URL</key><string>​https://apps.applozic.com​</string>
<key>AL_KBASE_URL</key><string>​https://​apps.applozic.com​</string>
<key>AL_MQTT_PORT</key><string>​1883​</string> ​// Do not change this
<key>AL_MQTT_URL</key><string>​apps.applozic.com​</string>
</dict>

Then open ALChatManager.m and inside ALDefaultChatViewSettings method add the following lines:

[self getApplicationBaseURL];
[ALApplozicSettings enableS3StorageService:YES];

Then try uninstalling and reinstalling your app and it should work.

**Comment by sureshMopidevi** [comment]
I haven't found the following method in ApplozicSwift
`[self getApplicationBaseURL];`
in swift : `self.getApplicationBaseURL`
